-- return {
--   "mattn/emmet-vim",
--   ft = {
--     "html",
--     "css",
--     "javascript",
--     "javascriptreact",
--     "typescriptreact",
--     "vue",
--     "php",
--     "blade",
--     "svelte",
--     "smarty",
--     "tpl",
--   },
--   config = function()
--     -- Emmet keybinding
--     vim.api.nvim_set_keymap("i", "<C-e>", "<C-y>,", { noremap = true, silent = true })
--
--     -- Optional emmet config
--     vim.g.user_emmet_leader_key = "<C-e>"
--     vim.g.user_emmet_settings = {}
--   end,
-- }

return {}
